// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ue2DqpcB4wwXyOiPyZw0Yc5WqjYskyM',
    appId: '1:126531548:web:d20bd095a3247781c54119',
    messagingSenderId: '126531548',
    projectId: 'mynotes-22437',
    authDomain: 'mynotes-22437.firebaseapp.com',
    storageBucket: 'mynotes-22437.appspot.com',
    measurementId: 'G-J5WWKGZBYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_QHDdwiH2eqs6z2I9q6ixhryhAeUsnY',
    appId: '1:126531548:android:7d80c0ff633df6c9c54119',
    messagingSenderId: '126531548',
    projectId: 'mynotes-22437',
    storageBucket: 'mynotes-22437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDryF18HEOsrE8fBRDeTHUAY4fiS-Ohre4',
    appId: '1:126531548:ios:f8f62f6874f3481ec54119',
    messagingSenderId: '126531548',
    projectId: 'mynotes-22437',
    storageBucket: 'mynotes-22437.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDryF18HEOsrE8fBRDeTHUAY4fiS-Ohre4',
    appId: '1:126531548:ios:9ff36a4afa468d49c54119',
    messagingSenderId: '126531548',
    projectId: 'mynotes-22437',
    storageBucket: 'mynotes-22437.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
